import { Scholarship, Application, StudentProfile, AuditLog, VaultDocument, NotificationItem } from "./types";

export const demoPersonas: StudentProfile[] = [
  {
    id: "std-2026-01",
    email: "priya.sharma@university.edu",
    fullName: "Priya Sharma",
    rollNo: "2024CSB1089",
    department: "Computer Science & Engineering",
    gpa: 3.92,
    annualIncome: 180000,
    category: "High Merit & AI Track",
    enrollmentYear: 2024,
    aadhaarNumber: "548692147305",
    phone: "+91 98401 23456",
    digiLockerVerified: true,
  },
  {
    id: "std-2026-02",
    email: "rahul.verma@university.edu",
    fullName: "Rahul Verma",
    rollNo: "2023ECE1042",
    department: "Electronics & Communication",
    gpa: 3.45,
    annualIncome: 120000,
    category: "Need-Based Financial Aid",
    enrollmentYear: 2023,
    aadhaarNumber: "314589206471",
    phone: "+91 97123 45678",
    digiLockerVerified: true,
  },
  {
    id: "std-2026-03",
    email: "rohan.gupta@university.edu",
    fullName: "Rohan Gupta",
    rollNo: "2025MECH1011",
    department: "Mechanical Engineering",
    gpa: 3.80,
    annualIncome: 240000,
    category: "First-Generation Scholar",
    enrollmentYear: 2025,
    aadhaarNumber: "892017453302",
    phone: "+91 98234 56789",
    digiLockerVerified: true,
  },
  {
    id: "std-2026-04",
    email: "maya.patel@university.edu",
    fullName: "Maya Patel",
    rollNo: "2024BIO2003",
    department: "Biotechnology & Life Sciences",
    gpa: 3.95,
    annualIncome: 310000,
    category: "Women in STEM & Research",
    enrollmentYear: 2024,
    aadhaarNumber: "672190431184",
    phone: "+91 99112 34567",
    digiLockerVerified: true,
  },
  {
    id: "std-2026-05",
    email: "sanjay.p@iitd.ac.in",
    fullName: "Sanjay P",
    rollNo: "2024CS108",
    department: "Computer Science & Engineering",
    gpa: 8.84,
    annualIncome: 180000,
    category: "Backward Class (BC) • OBC-NCL",
    enrollmentYear: 2024,
    aadhaarNumber: "492018474290",
    phone: "+91 98412 89012",
    digiLockerVerified: true,
  },
];

export const initialStudent: StudentProfile = demoPersonas[0];

export const initialScholarships: Scholarship[] = [
  {
    id: "sch-101",
    title: "NextGen AI & Cloud Computing Fellowship",
    description: "Annual academic grant and research fellowship for undergraduate students with outstanding performance in Computer Science, Data Engineering, and Artificial Intelligence.",
    category: "STEM & Research",
    awardAmount: 120000,
    totalSlots: 5,
    remainingSlots: 3,
    status: "OPEN",
    deadline: "2026-10-31",
    minGpa: 3.70,
    maxIncome: 450000,
    eligibleDepartments: ["Computer Science & Engineering", "Information Technology", "Data Science"],
    createdBy: "admissions@scholarhub.edu",
    createdAt: "2026-09-01",
    updatedAt: "2026-09-20",
  },
  {
    id: "sch-102",
    title: "University Access & Opportunity Grant",
    description: "Need-based financial aid designed to support first-generation college students and families overcoming economic barriers.",
    category: "Financial Need",
    awardAmount: 75000,
    totalSlots: 8,
    remainingSlots: 4,
    status: "OPEN",
    deadline: "2026-11-15",
    minGpa: 3.00,
    maxIncome: 250000,
    eligibleDepartments: ["All Departments"],
    createdBy: "admissions@scholarhub.edu",
    createdAt: "2026-09-05",
    updatedAt: "2026-09-22",
  },
  {
    id: "sch-103",
    title: "Women in STEM Leadership Award",
    description: "Dedicated fellowship empowering female leaders in engineering, mathematics, and technological innovations.",
    category: "Diversity & Leadership",
    awardAmount: 150000,
    totalSlots: 4,
    remainingSlots: 2,
    status: "OPEN",
    deadline: "2026-10-15",
    minGpa: 3.50,
    maxIncome: 500000,
    eligibleDepartments: ["Computer Science & Engineering", "Electronics & Communication", "Biotechnology & Life Sciences", "Mechanical Engineering"],
    createdBy: "admissions@scholarhub.edu",
    createdAt: "2026-09-02",
    updatedAt: "2026-09-21",
  },
  {
    id: "sch-104",
    title: "Chancellor's Highest Academic Merit Honors",
    description: "Prestigious institutional honors grant awarded to top 1% academic performers with significant thesis contributions.",
    category: "Academic Merit",
    awardAmount: 200000,
    totalSlots: 2,
    remainingSlots: 0,
    status: "CLOSED",
    deadline: "2026-09-20",
    minGpa: 3.90,
    maxIncome: null,
    eligibleDepartments: ["All Departments"],
    createdBy: "chancellor@scholarhub.edu",
    createdAt: "2026-08-15",
    updatedAt: "2026-09-20",
  },
  {
    id: "sch-105",
    title: "Sustainable Clean Tech & Urban Innovation Grant",
    description: "Sponsorship for breakthrough projects in renewable energy, circular economy, and sustainable urban infrastructure.",
    category: "STEM & Research",
    awardAmount: 90000,
    totalSlots: 6,
    remainingSlots: 5,
    status: "OPEN",
    deadline: "2026-12-01",
    minGpa: 3.20,
    maxIncome: 350000,
    eligibleDepartments: ["Mechanical Engineering", "Civil Engineering", "Biotechnology & Life Sciences"],
    createdBy: "research@scholarhub.edu",
    createdAt: "2026-09-10",
    updatedAt: "2026-09-22",
  },
];

export const initialApplications: Application[] = [];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    action: "SCHOLARSHIP_PUBLISHED",
    entity: "Scholarship",
    entityId: "sch-101",
    performedBy: "admissions@scholarhub.edu",
    details: "Created NextGen AI & Cloud Computing Fellowship with 5 total award slots (₹1,20,000/ea).",
    timestamp: "2026-09-01T10:00:00Z",
  },
  {
    id: "log-2",
    action: "AWARD_APPROVED",
    entity: "Application",
    entityId: "app-201",
    performedBy: "Dr. Evelyn Vance (Chair)",
    details: "Approved scholarship for Priya Sharma. Remaining slots decremented to 3.",
    timestamp: "2026-09-21T14:30:00Z",
  },
  {
    id: "log-3",
    action: "AWARD_APPROVED",
    entity: "Application",
    entityId: "app-204",
    performedBy: "Dr. Evelyn Vance (Chair)",
    details: "Approved scholarship for Maya Patel. Remaining slots decremented to 2.",
    timestamp: "2026-09-22T09:15:00Z",
  },
  {
    id: "log-4",
    action: "SCHOLARSHIP_CLOSED",
    entity: "Scholarship",
    entityId: "sch-104",
    performedBy: "Automated System Trigger",
    details: "Chancellor's Highest Academic Merit Honors awarded all 2 slots. Status transitioned to CLOSED.",
    timestamp: "2026-09-20T17:00:00Z",
  },
];

export const initialVaultDocuments: VaultDocument[] = [
  // PRIYA SHARMA (std-2026-01)
  {
    id: "doc-01",
    studentId: "std-2026-01",
    title: "Annual Family Income Certificate",
    issuer: "Tahsildar Revenue Office (TN e-District)",
    fileName: "income_certificate_2026_signed.pdf",
    fileSize: "1.8 MB",
    fileType: "Revenue Authority Attestation",
    validity: "Valid till 31 Mar 2027",
    sha256Hash: "0x4a89c28919024fbd90218ab28e19c0018f4",
    metricLabel: "Certified Annual Income",
    metricValue: "₹1,80,000 / yr",
    isVerified: true,
    verifiedAt: "2026-09-10",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 4,
    extractedIdentifier: "TN-REV/2026/0948215",
    fileUrl: "/specimens/income.svg",
    tamperSummary: "All Indian statutory checksums, revenue authorities, and identity tokens verified genuine.",
    checks: [
      { checkName: "State e-District Registry (Tamil Nadu)", passed: true, details: "Recognized legitimate certificate serial format TN-REV/2026." },
      { checkName: "Revenue Authority Validity Window", passed: true, details: "Active statutory validity through 31 Mar 2027." },
      { checkName: "Identity Cross-Reconciliation", passed: true, details: "High identity concordance (100% match) with Priya Sharma." },
      { checkName: "SHA-256 Byte Integrity Scan", passed: true, details: "Tamper-proof hash matched with state repository." },
    ],
  },
  {
    id: "doc-02",
    studentId: "std-2026-01",
    title: "Official Academic Transcript",
    issuer: "IIT Delhi Examination Cell • Dean Academics",
    fileName: "Verified_Academic_Transcript.pdf",
    fileSize: "2.4 MB",
    fileType: "Institutional Grade Sheet",
    validity: "Permanent Academic Record",
    sha256Hash: "0x89dc71092efb119a018742ca899017e891",
    metricLabel: "Cumulative CGPA",
    metricValue: "3.92 / 10.00 (Top 2%)",
    isVerified: true,
    verifiedAt: "2026-09-12",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "2024CSB1089",
    fileUrl: "/specimens/marksheet.svg",
    tamperSummary: "Dean of Academics digital watermark & CGPA boundary checks fully validated.",
    checks: [
      { checkName: "CGPA/Marks Numerical Boundary Sanity", passed: true, details: "CGPA 3.92 within valid range." },
      { checkName: "Institutional Roll Number Validation", passed: true, details: "Roll number 2024CSB1089 verified." },
      { checkName: "Identity Match", passed: true, details: "Matches registered student Priya Sharma." },
    ],
  },
  {
    id: "doc-03",
    studentId: "std-2026-01",
    title: "Aadhaar Biometric e-KYC Identity Token",
    issuer: "UIDAI Authority • DBT NPCI Bridge",
    fileName: "aadhaar_ekyc_tokenized.xml",
    fileSize: "420 KB",
    fileType: "National Identity Verification",
    validity: "Active & Tokenized",
    sha256Hash: "0x12a884f09a1288cba8019b78a9c801e7a1",
    metricLabel: "DBT Mapping",
    metricValue: "SBI A/C ****4819 (Active)",
    isVerified: true,
    verifiedAt: "2026-09-01",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "5486 9214 7305",
    fileUrl: "/specimens/aadhaar.png",
    tamperSummary: "UIDAI Verhoeff Checksum (Dihedral D5) passed. Linked with NPCI DBT mapper.",
    checks: [
      { checkName: "UIDAI Verhoeff Checksum (Dihedral D5)", passed: true, details: "12-digit Aadhaar passed Verhoeff parity checksum." },
      { checkName: "UIDAI National Format Conformity", passed: true, details: "Standard 12-digit UIDAI block structure." },
      { checkName: "NPCI DBT Bank Bridge", passed: true, details: "Aadhaar linked to State Bank of India IFSC SBIN0001423." },
    ],
  },
  {
    id: "doc-04",
    studentId: "std-2026-01",
    title: "Institutional Bonafide Certificate (2026-27)",
    issuer: "Office of the Dean of Academic Affairs • IIT Delhi",
    fileName: "IITD_Bonafide_AY26-27.pdf",
    fileSize: "1.2 MB",
    fileType: "Institutional Attestation",
    validity: "Academic Year 2026-27",
    sha256Hash: "0x89ab1024fbd90218ab28e19c0018f4a1239",
    metricLabel: "Attestation Level",
    metricValue: "Registrar Match 100%",
    isVerified: true,
    verifiedAt: "2026-09-14",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "IITD/ACAD/2026/BF-8912",
    fileUrl: "/specimens/bonafide.svg",
    tamperSummary: "Registrar signature, dean embossed golden seal and serial reference validated.",
    checks: [
      { checkName: "Institutional Seal Dihedral Parity", passed: true, details: "Official IIT Delhi Dean seal recognized." },
      { checkName: "Academic Term Concordance", passed: true, details: "Term AY 2026-27 current and active." },
      { checkName: "Student Registry Match", passed: true, details: "2024CSB1089 Priya Sharma matched." },
    ],
  },
  {
    id: "doc-04-caste",
    studentId: "std-2026-01",
    title: "Community / Caste Certificate (OBC-NCL)",
    issuer: "Revenue Dept • Govt of Tamil Nadu",
    fileName: "community_cert_tahsildar.pdf",
    fileSize: "1.2 MB",
    fileType: "OBC - Non-Creamy Layer (NCL)",
    validity: "Permanent Validity",
    sha256Hash: "0x289fa819024fbd90218ab28e19c0018f4a12",
    metricLabel: "Declared Quota",
    metricValue: "Backward Class (BC)",
    isVerified: true,
    verifiedAt: "2026-09-08",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "TN-COMM/2026/088219",
    fileUrl: "/specimens/caste.svg",
    tamperSummary: "Government Gazette seal and Tahsildar digital signing token intact.",
    checks: [
      { checkName: "Tahsildar Digital Signature & Barcode", passed: true, details: "PKI Digital signature cryptographically verified." },
      { checkName: "OBC-NCL Central List Gazette Match", passed: true, details: "Matches Central OBC Reservation notification 2026." },
    ],
  },
  {
    id: "doc-04-bank",
    studentId: "std-2026-01",
    title: "Bank Passbook & DBT Bridge Verification",
    issuer: "State Bank of India • NPCI Central Mapper",
    fileName: "sbi_passbook_dbt_seeded.pdf",
    fileSize: "850 KB",
    fileType: "Savings Bank Account & DBT Proof",
    validity: "Active & Seeded",
    sha256Hash: "0x77ab19024fbd90218ab28e19c0018f4a1239",
    metricLabel: "Active Disbursement Bank",
    metricValue: "State Bank of India (A/C ****4819)",
    isVerified: true,
    verifiedAt: "2026-09-02",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "SBIN0001423 / 4819",
    fileUrl: "/specimens/passbook.svg",
    tamperSummary: "UIDAI Verhoeff Checksum passed. NPCI DBT Bank Bridge active for direct transfers.",
    checks: [
      { checkName: "NPCI DBT Bank Bridge Active", passed: true, details: "State Bank of India (A/C ****4819) DBT Seeded." },
      { checkName: "IFSC Code Validation", passed: true, details: "SBIN0001423 IIT Delhi Hauz Khas Branch." },
    ],
  },

  // RAHUL VERMA (std-2026-02)
  {
    id: "doc-05",
    studentId: "std-2026-02",
    title: "Annual Family Income Certificate",
    issuer: "Nadakacheri Revenue Office (KA e-District)",
    fileName: "rahul_income_cert_2026.pdf",
    fileSize: "1.4 MB",
    fileType: "Revenue Authority Attestation",
    validity: "Valid till 31 Mar 2027",
    sha256Hash: "0x77c290a184f09a1288cba8019b78a9c801",
    metricLabel: "Certified Annual Income",
    metricValue: "₹1,20,000 / yr",
    isVerified: true,
    verifiedAt: "2026-09-05",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 2,
    extractedIdentifier: "KA-REV/2026/0881924",
    tamperSummary: "Karnataka Nadakacheri revenue attestation verified genuine.",
    checks: [
      { checkName: "Nadakacheri State Portal Check", passed: true, details: "Serial format KA-REV/2026 matched." },
      { checkName: "Identity Match", passed: true, details: "Matches registered student Rahul Verma." },
    ],
  },
  {
    id: "doc-06",
    studentId: "std-2026-02",
    title: "Official Academic Transcript",
    issuer: "National Institute of Technology • Dean Academics",
    fileName: "Rahul_Transcript_ECE.pdf",
    fileSize: "2.1 MB",
    fileType: "Institutional Grade Sheet",
    validity: "Permanent Academic Record",
    sha256Hash: "0x44a19b882190a184f09a1288cba8019b78",
    metricLabel: "Cumulative CGPA",
    metricValue: "3.45 / 10.00",
    isVerified: true,
    verifiedAt: "2026-09-08",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "2023ECE1042",
    tamperSummary: "Department of ECE academic stamp verified.",
    checks: [
      { checkName: "Roll Number Verification", passed: true, details: "2023ECE1042 verified active." },
      { checkName: "CGPA Sanity Check", passed: true, details: "3.45 CGPA verified." },
    ],
  },
  {
    id: "doc-07",
    studentId: "std-2026-02",
    title: "Aadhaar e-KYC Identity Verification",
    issuer: "UIDAI Authority • Canara Bank DBT Bridge",
    fileName: "rahul_aadhaar_token.xml",
    fileSize: "380 KB",
    fileType: "National Identity Verification",
    validity: "Active & Tokenized",
    sha256Hash: "0x9923bb190a184f09a1288cba8019b78a9c",
    metricLabel: "DBT Mapping",
    metricValue: "Canara Bank ****6471 (Active)",
    isVerified: true,
    verifiedAt: "2026-09-02",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "3145 8920 6471",
    tamperSummary: "UIDAI Verhoeff Checksum verified.",
    checks: [
      { checkName: "UIDAI Verhoeff Checksum", passed: true, details: "12-digit Aadhaar verified." },
    ],
  },

  // ROHAN GUPTA (std-2026-03)
  {
    id: "doc-08",
    studentId: "std-2026-03",
    title: "Income & First-Generation Learner Certificate",
    issuer: "Maha e-Seva Kendra (Maharashtra)",
    fileName: "rohan_first_gen_cert.pdf",
    fileSize: "1.9 MB",
    fileType: "Socio-Economic Certificate",
    validity: "Valid till 31 Mar 2027",
    sha256Hash: "0x55d812bb190a184f09a1288cba8019b78a",
    metricLabel: "Certified Annual Income",
    metricValue: "₹2,40,000 / yr",
    isVerified: true,
    verifiedAt: "2026-09-11",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 3,
    extractedIdentifier: "MH-REV/2026/0419201",
    tamperSummary: "Maharashtra Revenue Gazette stamp verified genuine.",
    checks: [
      { checkName: "Maha e-Seva Verification", passed: true, details: "Serial MH-REV/2026 matched." },
    ],
  },
  {
    id: "doc-09",
    studentId: "std-2026-03",
    title: "Official Academic Transcript",
    issuer: "College of Engineering • Examination Cell",
    fileName: "Rohan_Gupta_Transcript_ME.pdf",
    fileSize: "2.3 MB",
    fileType: "Institutional Grade Sheet",
    validity: "Permanent Academic Record",
    sha256Hash: "0x33b901a184f09a1288cba8019b78a9c801",
    metricLabel: "Cumulative CGPA",
    metricValue: "3.80 / 10.00",
    isVerified: true,
    verifiedAt: "2026-09-14",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "2025MECH1011",
    tamperSummary: "Mechanical Engineering academic dean seal validated.",
    checks: [
      { checkName: "Roll Number Verification", passed: true, details: "2025MECH1011 active." },
    ],
  },

  // MAYA PATEL (std-2026-04)
  {
    id: "doc-10",
    studentId: "std-2026-04",
    title: "Income & Research Patent Attestation",
    issuer: "Delhi e-District Revenue Department",
    fileName: "maya_income_patent_cert.pdf",
    fileSize: "2.5 MB",
    fileType: "Revenue & Patent Attestation",
    validity: "Valid till 31 Mar 2027",
    sha256Hash: "0x11a84f09a1288cba8019b78a9c801e7a199",
    metricLabel: "Certified Annual Income",
    metricValue: "₹3,10,000 / yr",
    isVerified: true,
    verifiedAt: "2026-09-09",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 1,
    extractedIdentifier: "DL-REV/2026/0991204",
    tamperSummary: "Delhi e-District Revenue authority validated.",
    checks: [
      { checkName: "Delhi e-District Verification", passed: true, details: "DL-REV/2026 matched." },
    ],
  },
  {
    id: "doc-11",
    studentId: "std-2026-04",
    title: "Official Academic Transcript",
    issuer: "Faculty of Life Sciences • BioTech Dept",
    fileName: "Maya_Patel_Transcript.pdf",
    fileSize: "2.0 MB",
    fileType: "Institutional Grade Sheet",
    validity: "Permanent Academic Record",
    sha256Hash: "0x99e812bb190a184f09a1288cba8019b78a9",
    metricLabel: "Cumulative CGPA",
    metricValue: "3.95 / 10.00 (Top 1%)",
    isVerified: true,
    verifiedAt: "2026-09-12",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "2024BIO2003",
    tamperSummary: "Top departmental rank verified.",
    checks: [
      { checkName: "Roll Number Verification", passed: true, details: "2024BIO2003 active." },
    ],
  },

  // SANJAY P (std-2026-05) - Stitch Document Vault Spec
  {
    id: "doc-12",
    studentId: "std-2026-05",
    title: "Annual Family Income Certificate",
    issuer: "Tahsildar Revenue Office (TN e-District)",
    fileName: "income_certificate_2024_signed.pdf",
    fileSize: "1.8 MB",
    fileType: "Revenue Authority Attestation",
    validity: "Valid till 31 Mar 2027",
    sha256Hash: "0x4a89c28919024fbd90218ab28e19c0018f4",
    metricLabel: "Annual Income",
    metricValue: "₹1,80,000",
    isVerified: true,
    verifiedAt: "2026-09-10",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 2,
    extractedIdentifier: "TN-REV/2026/0948215",
    fileUrl: "/specimens/income.svg",
    tamperSummary: "All Indian statutory checksums, revenue authorities, and identity tokens verified genuine.",
    checks: [
      { checkName: "State e-District Registry (Tamil Nadu)", passed: true, details: "Recognized legitimate certificate serial format TN-REV/2026." },
      { checkName: "Revenue Authority Validity Window", passed: true, details: "Active statutory validity through 31 Mar 2027." },
      { checkName: "Identity Cross-Reconciliation", passed: true, details: "High identity concordance (100% match) with Sanjay P." },
      { checkName: "SHA-256 Byte Integrity Scan", passed: true, details: "Tamper-proof hash matched with state repository." },
    ],
  },
  {
    id: "doc-13",
    studentId: "std-2026-05",
    title: "Community & Caste Certificate",
    issuer: "Revenue Dept • Govt of Tamil Nadu",
    fileName: "community_cert_tahsildar.pdf",
    fileSize: "1.2 MB",
    fileType: "OBC - Non-Creamy Layer (NCL)",
    validity: "Permanent Validity",
    sha256Hash: "0x289fa819024fbd90218ab28e19c0018f4a12",
    metricLabel: "Declared Quota",
    metricValue: "Backward Class (BC)",
    isVerified: true,
    verifiedAt: "2026-09-08",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "TN-COMM/2026/088219",
    fileUrl: "/specimens/caste.svg",
    tamperSummary: "Government Gazette seal and Tahsildar digital signing token intact.",
    checks: [
      { checkName: "Tahsildar Digital Signature & Barcode", passed: true, details: "PKI Digital signature cryptographically verified." },
      { checkName: "OBC-NCL Central List Gazette Match", passed: true, details: "Matches Central OBC Reservation notification 2026." },
    ],
  },
  {
    id: "doc-14",
    studentId: "std-2026-05",
    title: "B.E CSE 1st Year Consolidated Marksheet",
    issuer: "Indian Institute of Technology Delhi",
    fileName: "iitd_semester_marksheet_transcript.pdf",
    fileSize: "2.4 MB",
    fileType: "AICTE / IITD API Record",
    validity: "Permanent Academic Record",
    sha256Hash: "0x9812acb9024fbd90218ab28e19c0018f477e",
    metricLabel: "Academic Standing",
    metricValue: "8.24 / 10.0 CGPA",
    isVerified: true,
    verifiedAt: "2026-09-12",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "2024CS108",
    fileUrl: "/specimens/marksheet.svg",
    tamperSummary: "IIT Delhi Examination Cell API synced. Dean Academic watermark validated.",
    checks: [
      { checkName: "AICTE / UGC 10-Point Scale Validation", passed: true, details: "CGPA 8.24 verified genuine." },
      { checkName: "Institutional Roll Number Validation", passed: true, details: "Roll number 2024CS108 active in IIT Delhi student register." },
    ],
  },
  {
    id: "doc-15",
    studentId: "std-2026-05",
    title: "Aadhaar e-KYC & NPCI Mandate",
    issuer: "Direct Benefit Transfer (DBT) Route • UIDAI & NPCI",
    fileName: "npci_aadhaar_mandate_signed.pdf",
    fileSize: "850 KB",
    fileType: "UIDAI & NPCI Bank Bridge",
    validity: "Active & Tokenized",
    sha256Hash: "0x77ab19024fbd90218ab28e19c0018f4a1239",
    metricLabel: "Active Disbursement Bank",
    metricValue: "State Bank of India (A/C ********8912)",
    isVerified: true,
    verifiedAt: "2026-09-02",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "4920 1847 4290",
    fileUrl: "/specimens/aadhaar.png",
    tamperSummary: "UIDAI Verhoeff Checksum passed. NPCI DBT Bank Bridge active for direct transfers.",
    checks: [
      { checkName: "UIDAI Verhoeff Checksum (Dihedral D5)", passed: true, details: "12-digit Aadhaar passed Verhoeff parity checksum." },
      { checkName: "NPCI DBT Bank Bridge Active", passed: true, details: "State Bank of India (A/C ********8912) DBT Seeded." },
    ],
  },
  {
    id: "doc-16",
    studentId: "std-2026-05",
    title: "Institutional Bonafide Certificate (2026-27)",
    issuer: "Office of the Dean of Academic Affairs • IIT Delhi",
    fileName: "iitd_bonafide_sanjay.pdf",
    fileSize: "1.1 MB",
    fileType: "Institutional Attestation",
    validity: "Academic Year 2026-27",
    sha256Hash: "0x33441024fbd90218ab28e19c0018f4a1239",
    metricLabel: "Attestation Level",
    metricValue: "Dean Verified",
    isVerified: true,
    verifiedAt: "2026-09-14",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "IITD/ACAD/2026/BF-8913",
    fileUrl: "/specimens/bonafide.svg",
    tamperSummary: "IIT Delhi Dean seal and registrar attestation validated.",
    checks: [
      { checkName: "Seal Dihedral Parity", passed: true, details: "IIT Delhi Dean seal recognized." },
    ],
  },
  {
    id: "doc-17",
    studentId: "std-2026-05",
    title: "Bank Account Passbook & DBT Proof",
    issuer: "State Bank of India • NPCI Central Mapper",
    fileName: "sbi_passbook_sanjay.pdf",
    fileSize: "820 KB",
    fileType: "Savings Bank Account & DBT Proof",
    validity: "Active & Seeded",
    sha256Hash: "0x9911ab19024fbd90218ab28e19c0018f4a12",
    metricLabel: "Active Disbursement Bank",
    metricValue: "State Bank of India (A/C ********8912)",
    isVerified: true,
    verifiedAt: "2026-09-02",
    verdict: "GENUINE_VERIFIED",
    fraudRiskScore: 0,
    extractedIdentifier: "SBIN0001423 / 8912",
    fileUrl: "/specimens/passbook.svg",
    tamperSummary: "UIDAI Verhoeff Checksum passed. NPCI DBT Bank Bridge active.",
    checks: [
      { checkName: "NPCI DBT Bank Bridge Active", passed: true, details: "State Bank of India DBT Seeded." },
    ],
  },
];

export const initialNotifications: NotificationItem[] = [];
