import { BusinessEntity, WorkflowTask, AuditLog, UserProfile, SystemMetrics } from "./types";

export const initialProfiles: UserProfile[] = [
  {
    id: "usr-01",
    email: "lead.architect@bizhack.io",
    fullName: "Alex Rivera",
    role: "ADMIN",
    department: "Enterprise Systems",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "usr-02",
    email: "sarah.chen@bizhack.io",
    fullName: "Sarah Chen",
    role: "MANAGER",
    department: "Operations & Logistics",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "usr-03",
    email: "marcus.vance@bizhack.io",
    fullName: "Marcus Vance",
    role: "ANALYST",
    department: "Financial Risk",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const initialEntities: BusinessEntity[] = [
  {
    id: "ent-101",
    name: "Automated Supply Chain Disruption Mitigator",
    code: "SUP-2026-X1",
    category: "Supply Chain",
    status: "ACTIVE",
    priority: "CRITICAL",
    ownerId: "usr-01",
    ownerName: "Alex Rivera",
    budget: 145000,
    metadata: { complianceScore: 98, region: "APAC & EMEA" },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "ent-102",
    name: "Real-time B2B Invoice Reconciliation Gateway",
    code: "FIN-2026-04",
    category: "FinTech & Billing",
    status: "ACTIVE",
    priority: "HIGH",
    ownerId: "usr-02",
    ownerName: "Sarah Chen",
    budget: 82000,
    metadata: { processedVolume: "$4.2M", accuracyRate: "99.94%" },
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: "ent-103",
    name: "Enterprise Compliance & Audit Trail Engine",
    code: "GOV-2026-09",
    category: "Governance & ESG",
    status: "PENDING_REVIEW",
    priority: "HIGH",
    ownerId: "usr-03",
    ownerName: "Marcus Vance",
    budget: 65000,
    metadata: { auditFrequency: "Daily", automatedRules: 42 },
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 14).toISOString(),
  },
  {
    id: "ent-104",
    name: "Predictive Asset Lifecycle Tracker",
    code: "OPS-2026-12",
    category: "Operations",
    status: "COMPLETED",
    priority: "MEDIUM",
    ownerId: "usr-02",
    ownerName: "Sarah Chen",
    budget: 54000,
    metadata: { uptimeGuarantee: "99.99%", telemetryFrequency: "500ms" },
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const initialTasks: WorkflowTask[] = [
  {
    id: "tsk-01",
    entityId: "ent-101",
    title: "Configure multi-region failover endpoints",
    description: "Establish automated latency-based fallback routes across US-East and EU-Central nodes.",
    assignee: "Alex Rivera",
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    completionRate: 75,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "tsk-02",
    entityId: "ent-102",
    title: "Ingest vendor XML/EDI billing feeds",
    description: "Implement high-throughput stream parser with schema auto-correction.",
    assignee: "Sarah Chen",
    status: "DONE",
    priority: "HIGH",
    dueDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    completionRate: 100,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "tsk-03",
    entityId: "ent-103",
    title: "Cryptographic hash chain verification for logs",
    description: "Ensure tamper-evident SHA-256 verification on every audited state transition.",
    assignee: "Marcus Vance",
    status: "IN_REVIEW",
    priority: "HIGH",
    dueDate: new Date(Date.now() + 86400000 * 1).toISOString(),
    completionRate: 90,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "tsk-04",
    entityId: "ent-101",
    title: "Telemetry metrics health dashboard integration",
    description: "Feed real-time event alerts directly into executive overview telemetry.",
    assignee: "Alex Rivera",
    status: "TODO",
    priority: "MEDIUM",
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    completionRate: 0,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const initialLogs: AuditLog[] = [
  {
    id: "log-01",
    action: "SYSTEM_INITIALIZED",
    entity: "SystemCore",
    entityId: "SYS-INIT",
    performedBy: "Alex Rivera",
    details: "Initialized Next.js 16 App Router & Local Storage Provider Engine.",
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: "log-02",
    action: "STATUS_CHANGE",
    entity: "BusinessEntity",
    entityId: "ent-102",
    performedBy: "Sarah Chen",
    details: "Promoted B2B Reconciliation Gateway to ACTIVE workflow state.",
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "log-03",
    action: "TASK_COMPLETED",
    entity: "WorkflowTask",
    entityId: "tsk-02",
    performedBy: "Sarah Chen",
    details: "Completed ingest parser tests with 100% test coverage.",
    timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
];

export const initialMetrics: SystemMetrics = {
  totalEntities: 4,
  activeWorkflows: 2,
  completedTasks: 18,
  pendingReviews: 3,
  efficiencyScore: 94.8,
  avgResolutionTimeHours: 3.4,
};
